version: 2
jobs:
  build:
    working_directory: ~/django-enum-choices
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r django_enum_choices/requirements.txt
            py.test
